tls:
  options:
    modern:
      minVersion: VersionTLS13
      sniStrict: false
      curvePreferences:
        - CurveP256
        - CurveP384
http:
  middlewares:
    rate-limit:
      rateLimit:
        average: 100
        burst: 50
    secure-headers-backend:
      headers:
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        contentTypeNosniff: true
        customResponseHeaders:
          Server: ""
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
          - "PATCH"
        accessControlAllowHeaders:
          - "Authorization"
          - "Content-Type"
          - "Origin"
          - "Accept"
        accessControlExposeHeaders:
          - "Content-Length"
          - "Content-Range"
        accessControlAllowOriginList:
          - "https://dependencycontrol.local"
        accessControlAllowCredentials: true
        accessControlMaxAge: 100
        addVaryHeader: true
    secure-headers-frontend:
      headers:
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        contentTypeNosniff: true
        customResponseHeaders:
          Server: ""
