apiVersion: v2
name: dependency-control
description: A Helm chart for Dependency Control with HA MongoDB, DragonflyDB Cache, and Traefik
type: application
version: 1.4.44
appVersion: "1.4.44"
icon: file://logo.png
annotations:
  artifacthub.io/license: MIT
dependencies:
  - name: community-operator
    version: 0.13.0
    repository: https://mongodb.github.io/helm-charts
    alias: mongodb-operator
    condition: mongodb-operator.enabled
  - name: psmdb-operator
    version: 1.21.3
    repository: https://percona.github.io/percona-helm-charts/
    condition: psmdb-operator.enabled
  - name: dragonfly
    version: "v1.35.1"
    repository: oci://ghcr.io/dragonflydb/dragonfly/helm
    condition: dragonfly.enabled
  - name: traefik
    version: 37.4.0
    repository: https://traefik.github.io/charts
    condition: traefik.enabled
  - name: cert-manager
    version: v1.19.2
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
