apiVersion: v2
name: dependency-control
description: A Helm chart for Dependency Control with HA MongoDB, DragonflyDB Cache, and Traefik
type: application
version: 1.2.2
appVersion: "1.2.2"
icon: file://logo.png
annotations:
  artifacthub.io/license: MIT
dependencies:
  - name: community-operator
    version: 0.13.0
    repository: https://mongodb.github.io/helm-charts
    alias: mongodb-operator
  - name: dragonfly
    version: "v1.35.1"
    repository: oci://ghcr.io/dragonflydb/dragonfly/helm
    condition: dragonfly.enabled
  - name: traefik
    version: 37.4.0
    repository: https://traefik.github.io/charts
    condition: traefik.enabled
