apiVersion: v2
name: dependency-control
description: A Helm chart for Dependency Control with HA MongoDB and Traefik
type: application
version: 0.1.7
appVersion: "0.1.7"
annotations:
  artifacthub.io/license: MIT
dependencies:
  - name: community-operator
    version: 0.13.0
    repository: https://mongodb.github.io/helm-charts
    alias: mongodb-operator
  - name: traefik
    version: 33.1.0
    repository: https://traefik.github.io/charts
    condition: traefik.enabled
