{{- if eq .Values.database.type "mongodb" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.cluster.name }}-user-password
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: {{ .Values.database.auth.password | quote }}
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: {{ .Values.database.cluster.name }}
  namespace: {{ .Release.Namespace }}
spec:
  members: {{ .Values.database.cluster.replicas }}
  type: ReplicaSet
  version: {{ .Values.database.mongodb.version }}
  security:
    authentication:
      modes: ["SCRAM"]
    {{- if .Values.global.tls.enabled }}
    tls:
      enabled: true
      optional: false
      certificateKeySecretRef:
        name: {{ .Values.database.cluster.name }}-tls
      caCertificateSecretRef:
        name: {{ include "dependency-control.caSecretName" . }}
    {{- end }}
  users:
    - name: {{ .Values.database.auth.username }}
      db: {{ .Values.database.auth.database }}
      passwordSecretRef:
        name: {{ .Values.database.cluster.name }}-user-password
      roles:
        - name: readWrite
          db: {{ .Values.database.auth.database }}
      scramCredentialsSecretName: {{ .Values.database.cluster.name }}-scram
  statefulSet:
    spec:
      template:
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - "{{ .Values.database.cluster.name }}-svc"
                  topologyKey: "kubernetes.io/hostname"
          containers:
            - name: mongod
              resources:
{{ toYaml .Values.database.cluster.resources | indent 16 }}
              securityContext:
                runAsNonRoot: true
                runAsUser: 2000
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: {{ .Values.database.cluster.persistence.size }}
            {{- if .Values.database.cluster.persistence.storageClass }}
            storageClassName: {{ .Values.database.cluster.persistence.storageClass }}
            {{- end }}
{{- end }}

