{{- if and (eq .Values.database.type "percona") .Values.database.percona.encryptionKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.cluster.name }}-encryption-key
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  encryption-key: {{ .Values.database.percona.encryptionKey | b64enc }}
{{- end }}
