{{- $isTraefik := or .Values.traefik.enabled (eq (.Values.ingress.className | default "") "traefik") -}}
{{- if and $isTraefik .Values.ingress.traefikMiddlewares.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "dependency-control.fullname" . }}-rate-limit
  labels:
    {{- include "dependency-control.labels" . | nindent 4 }}
spec:
  rateLimit:
    average: 100
    burst: 50

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "dependency-control.fullname" . }}-secure-headers-backend
  labels:
    {{- include "dependency-control.labels" . | nindent 4 }}
spec:
  headers:
    stsSeconds: 63072000
    stsIncludeSubdomains: true
    stsPreload: true
    contentTypeNosniff: true
    customResponseHeaders:
      Server: ""
{{- end }}
